In [69]:
import pandas as pd

In [70]:
import numpy as np

In [71]:
text='''Real madrid is set to win the UCL for the season . Benzema might win Balon dor . Salah might be the runner up'''


In [72]:
text

'Real madrid is set to win the UCL for the season . Benzema might win Balon dor . Salah might be the runner up'

In [73]:
import nltk

In [74]:
nltk.download ('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

tokenization

In [75]:
from nltk import sent_tokenize , word_tokenize

In [76]:
sent_tokenize(text)

['Real madrid is set to win the UCL for the season .',
 'Benzema might win Balon dor .',
 'Salah might be the runner up']

In [77]:
word_list=word_tokenize(text)

In [78]:
word_list

['Real',
 'madrid',
 'is',
 'set',
 'to',
 'win',
 'the',
 'UCL',
 'for',
 'the',
 'season',
 '.',
 'Benzema',
 'might',
 'win',
 'Balon',
 'dor',
 '.',
 'Salah',
 'might',
 'be',
 'the',
 'runner',
 'up']

Stop Words Removal

In [79]:
from nltk.corpus import stopwords

In [80]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [81]:
 stopword_list = stopwords.words('english')

In [82]:
stopword_list

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [83]:
word_list=[word.lower() for word in word_list]

In [84]:
filterword_list=[]
for word in word_list:
  if word not in stopword_list:
    filterword_list.append(word)

In [85]:
filterword_list

['real',
 'madrid',
 'set',
 'win',
 'ucl',
 'season',
 '.',
 'benzema',
 'might',
 'win',
 'balon',
 'dor',
 '.',
 'salah',
 'might',
 'runner']

In [86]:
w1=[word for word in word_list if word not in stopword_list ]

In [87]:
w1

['real',
 'madrid',
 'set',
 'win',
 'ucl',
 'season',
 '.',
 'benzema',
 'might',
 'win',
 'balon',
 'dor',
 '.',
 'salah',
 'might',
 'runner']

stemming


In [88]:
from nltk.stem import PorterStemmer


In [89]:
stemmer= PorterStemmer()

In [90]:
stem_words=[stemmer.stem (word) for word in filterword_list]

In [91]:
stem_words

['real',
 'madrid',
 'set',
 'win',
 'ucl',
 'season',
 '.',
 'benzema',
 'might',
 'win',
 'balon',
 'dor',
 '.',
 'salah',
 'might',
 'runner']

Lemmatization


In [92]:
from nltk.stem import WordNetLemmatizer

In [93]:
lemmatizer=WordNetLemmatizer()

In [94]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [95]:
lemma_words=[lemmatizer.lemmatize(word) for word in filterword_list ]

In [96]:
lemma_words

['real',
 'madrid',
 'set',
 'win',
 'ucl',
 'season',
 '.',
 'benzema',
 'might',
 'win',
 'balon',
 'dor',
 '.',
 'salah',
 'might',
 'runner']

Part of Speech Tagging

In [97]:
from nltk import pos_tag

In [98]:
 nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [99]:
tag_list=pos_tag(lemma_words)

In [100]:
tag_list

[('real', 'JJ'),
 ('madrid', 'NN'),
 ('set', 'VBN'),
 ('win', 'VBP'),
 ('ucl', 'JJ'),
 ('season', 'NN'),
 ('.', '.'),
 ('benzema', 'NN'),
 ('might', 'MD'),
 ('win', 'VB'),
 ('balon', 'NN'),
 ('dor', 'NN'),
 ('.', '.'),
 ('salah', 'NN'),
 ('might', 'MD'),
 ('runner', 'VB')]

Bag of Words

In [144]:
from sklearn.feature_extraction.text import CountVectorizer

In [145]:
vectorizer=CountVectorizer()

In [146]:
sentence_list=sent_tokenize(text)

In [147]:
sentence_list

['Real madrid is set to win the UCL for the season .',
 'Benzema might win Balon dor .',
 'Salah might be the runner up']

In [148]:
vectorizer.fit(sentence_list)

CountVectorizer()

In [149]:
print('Vocabulary',vectorizer.vocabulary_)

Vocabulary {'real': 8, 'madrid': 6, 'is': 5, 'set': 12, 'to': 14, 'win': 17, 'the': 13, 'ucl': 15, 'for': 4, 'season': 11, 'benzema': 2, 'might': 7, 'balon': 0, 'dor': 3, 'salah': 10, 'be': 1, 'runner': 9, 'up': 16}


Encoding

In [150]:
vector=vectorizer.transform(sentence_list)

In [151]:

print (vector.toarray())

[[0 0 0 0 1 1 1 0 1 0 0 1 1 2 1 1 0 1]
 [1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0]]


In [152]:
features=vectorizer.get_feature_names_out()

In [153]:
doc_list=['doc1','doc2','doc3']

In [154]:
df=pd.DataFrame(vector.toarray(),index=sorted(doc_list),columns=features)

In [155]:
df

balon  be  benzema  dor  for  is  madrid  might  real  runner  salah  \
doc1      0   0        0    0    1   1       1      0     1       0      0   
doc2      1   0        1    1    0   0       0      1     0       0      0   
doc3      0   1        0    0    0   0       0      1     0       1      1   

      season  set  the  to  ucl  up  win  
doc1       1    1    2   1    1   0    1  
doc2       0    0    0   0    0   0    1  
doc3       0    0    1   0    0   1    0

Term Frequency and Inverse Document Frequency

In [110]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [127]:
vectorizer1=TfidfVectorizer()


In [128]:
vectorizer1.fit(sentence_list)

TfidfVectorizer()

In [129]:
print ('Vocabulary',vectorizer1.vocabulary_)

Vocabulary {'real': 8, 'madrid': 6, 'is': 5, 'set': 12, 'to': 14, 'win': 17, 'the': 13, 'ucl': 15, 'for': 4, 'season': 11, 'benzema': 2, 'might': 7, 'balon': 0, 'dor': 3, 'salah': 10, 'be': 1, 'runner': 9, 'up': 16}


In [130]:
vector=vectorizer1.transform(sentence_list)

In [116]:
print (vector.toarray())

[[0.         0.         0.         0.         0.30300252 0.30300252
  0.30300252 0.         0.30300252 0.         0.         0.30300252
  0.30300252 0.46088245 0.30300252 0.30300252 0.         0.23044123]
 [0.49047908 0.         0.49047908 0.49047908 0.         0.
  0.         0.37302199 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.37302199]
 [0.         0.44036207 0.         0.         0.         0.
  0.         0.3349067  0.         0.44036207 0.44036207 0.
  0.         0.3349067  0.         0.         0.44036207 0.        ]]


In [131]:
print ('Features',vectorizer1.get_feature_names_out)

Features <bound method CountVectorizer.get_feature_names_out of TfidfVectorizer()>


In [133]:
features=vectorizer.get_feature_names_out()

In [135]:
doc_list=['doc1','doc2','doc3']

In [136]:
df=pd.DataFrame(vector.toarray(),index=sorted(doc_list),columns=features)

In [137]:
df

balon        be   benzema       dor       for        is    madrid  \
doc1  0.000000  0.000000  0.000000  0.000000  0.303003  0.303003  0.303003   
doc2  0.490479  0.000000  0.490479  0.490479  0.000000  0.000000  0.000000   
doc3  0.000000  0.440362  0.000000  0.000000  0.000000  0.000000  0.000000   

         might      real    runner     salah    season       set       the  \
doc1  0.000000  0.303003  0.000000  0.000000  0.303003  0.303003  0.460882   
doc2  0.373022  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc3  0.334907  0.000000  0.440362  0.440362  0.000000  0.000000  0.334907   

            to       ucl        up       win  
doc1  0.303003  0.303003  0.000000  0.230441  
doc2  0.000000  0.000000  0.000000  0.373022  
doc3  0.000000  0.000000  0.440362  0.000000